/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_async_apkupdate_BsdiffUtils */

#ifndef _Included_com_async_apkupdate_BsdiffUtils
#define _Included_com_async_apkupdate_BsdiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_async_apkupdate_BsdiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_async_apkupdate_BsdiffUtils_genDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_async_apkupdate_BsdiffUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_async_apkupdate_BsdiffUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
